# An introduction to R and the United States Census 

```{r setup-ch1, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


This book is designed for practitioners interested in working efficiently with data from the United States Census Bureau. Census data are used widely in the United States across many research and applied fields, including education, business, journalism, and many others.  Until recently, the process of working with US Census data has commonly required the use of a wide array of web interfaces and software platforms to prepare, map, and present the data products.  The goal of this book is to illustrate the utility of the R programming language for handling these tasks, allowing Census data users to manage their projects in a single computing environment.  

The book focuses on two types of Census data products commonly used by practitioners: 

* __Aggregate data__, which involve counts or estimates released by the Census Bureau that are aggregated to some geographic unit of interest, such as a state; 
* __Microdata__, which are individual, anonymized Census records that commonly represent a sample of a given Census dataset.  

In turn, the book is organized into three general sections that cover key areas of interest for practitioners working with US Census data in R.  __Section I__ covers the process of working with Census data tables within R.  After a brief introduction to US Census Bureau data and the R computing environment, readers will learn how to acquire, wrangle, and visualize aggregate US Census data.  __Section II__ focuses on spatial Census data analysis.  Readers will learn about US Census Bureau spatial data, and then learn how to use this data to make maps, perform spatial analyses, and design spatial statistical and machine learning models.  __Section III__ covers Census datasets outside the decennial Census and American Community Survey.  In Section III, readers will learn how to use the Census Bureau's Public Use Microdata Series datasets and then model this data using specialized tools within R for working with complex survey samples.  Section III also covers historical Census data analysis and explores Census data resources outside the United States.  

## Census data: an overview 


## Census hierarchies 


## Applications of Census data analysis 


## What is R?



## R packages for Census data analysis 

With over 73,000 downloads from the RStudio CRAN mirror as of October 2017, the __acs__ package (Haber Glenn 2017) is one of the most widely-used tools for Census data access in R.  The acs package allows for access to both decennial Census and American Community Survey data, and includes a suite of tools to manage data downloads and calculate margins of error.  The __choroplethr__ package (Lamstein and Johnson 2017) wraps acs and __ggplot2__ to allow R users to rapidly create maps using Census and ACS data, and also provides access to the underlying data as well.  More recently, the __censusapi__ package (Recht 2017) helps R users access any of the US Census Bureau's data APIs.  While the censusapi package requires more knowledge of the underlying structure of the API to work, its breadth is unmatched among Census API packages in R. 

{give examples of each in this section}-


## Focus of the book (July 31)


